### ISSUE TITLE
Deserializing numeric strings

### ISSUE THREAD

**Issue by TheBiggerGuy** [Byron/google-apis-rs#211]
Currently the code tries to use numeric types for properties that "look" numeric like (e.g. "mediaItemsCount": "100") however current versions of _serde_ do not implicitly cast strings to numeric types.

# Example
```json
"mediaItemsCount": {
          "description": "[Output only] The number of media items in the album.",
          "format": "int64",
          "type": "string"
        }
```
The type gets converted to ```i64``` via the _type = "string"_ and _name contains "count"_. https://github.com/Byron/google-apis-rs/blob/8f0435ae4f8b1cfca65ec6374c60ced8b5080a18/src/mako/lib/util.py#L350

But then _serde_ now does not explicitly convert strings to numbers without a ```#[serde(deserialize_with = "from_str")]``` directive. https://github.com/serde-rs/json/issues/317#issuecomment-300251188

**Comment by TheBiggerGuy** [comment]
My thoughts are either:
### Remove the "smart" conversion attempt at let API users convert the Google numeric strings themself.
For:
* Many of the APIs require though into the correct Rust types (signed/unsigned and sizing) that might be better done in a non automated way
* Being "smart" often leads to more confusion and hidden "magic"

Against:
* It would force all consumers to write the same boilerplate code

### Fix it so _serde_ will convert the numeric strings to Rust numeric types.
For:
* Makes the Rust API a lot cleaner
* A place to centralise the wisdom of the cround on the best way to do it.

Against:
* Being "smart" often leads to more confusion and hidden "magic"
* Extra conversion steps would be required even if the consumer does not read that property.

**Comment by Byron** [comment]
What I understand is that the current '_smart_' behavior is broken if the latest serde is used, as automatic conversions don't happen anymore. However, this could be fixed with a custom deserializer as indicated by the referenced serde issue.

Keeping the smart behaviour would certrainly be nice if it always does the right thing, even though that is something I don't think can be achieved here. Particularly looking for 'Count' in some description seems like a ~~convenience~~ hack.

When looking at the example, it appears that even if the field is a string, additional type information is provided which could be a source of truth with associated smart conversions at least for strings. That would make the example work which uses `string` as type and `i64` as format used in the string.

For that matter, maybe a compromise is possible. Hacks that involve looking for keywords in descriptions should be removed, and there should be better use of the `format` information alongside the required serde deserializers and serializers.

@TheBiggerGuy I hope that adds something to this conversation. Even if a compromise is not possible, today I would lean towards the non-magical solution.

**Comment by TheBiggerGuy** [comment]
My current attempts have been to try and use the additional "format" information provided and add a custom deserializer. I believe this should work in all the cases I've looked into.

I am trying to
a) Find a way to use as much of the built-in serde deserializer as possible. We don't want a custom JSON parser.
B) work out any type conversation code. As this will be run in client app code it needs to be robust.
C) not increase the complexity of the current type code in Python.

**Comment by repi** [comment]
Have anyone experimented more with a solution for this? Been running into this issue as well

**Comment by Byron** [comment]
As far as this issue goes, I have removed the special cases indicated by this issue in a previous commit.
Thus the type is now correctly inferred as `String` which must be parsed by the user themselves. The reasoning is that it's better to have a working but cumbersome solution, than no working solution at all.

As this repository matures, we might be able to come up with better ways to deal with these things, and I would very much favor us being able to handle these parsing tasks for the user in the future.

**Comment by Byron** [comment]
@TheBiggerGuy Please feel free to reopen this issue in case some better ways of handling this are on the way, or if you think I closed this issue erroneously. Thanks for all your efforts thus far!
