### ISSUE TITLE
Google speech api - unable to get examples working

### ISSUE THREAD

**Issue by zelanter** [Byron/google-apis-rs#224]
Hi,

been struggling for a while to get this to work, including both my code and the examples from the documentation, and I ultimately get stuck with this error: "Token retrieval failed with error: Invalid Scope: 'no description provided'".

Please note that provided account has been deleted, so I had to provide my own client id and client secret.

I've reached a point where I just really need to know if anyone at all is getting this to work.

Thank you.

**Comment by Byron** [comment]
Indeed, one will need their own account information to use any of the APIs, as the 'default' one has since been removed by google.
Usually, when an account is provided with the given API enabled, and once the login succeeded, one can expect that the CLI will work for the most part. From there one can explore and probably start writing own code to write custom tools, or just use the CLI if it doing everything one needs.

If the CLI also gets the 'invalid scope' error, this might mean that the default scope for permissions as documented in the JSON schema that is used to generate the code is insufficient to perform the desired operation. In that case, one can always override the scope on the command-line to potentially raise privileges.

Please note that the initial login is always based on one or more scopes, so a new login might be required. That, however, should be managed automatically by the CLI.

I hope that helps a little. Please feel free to keep commenting on the closed issue.
