### ISSUE TITLE
google_pubsub1::Error is not compatible with failure

### ISSUE THREAD

**Issue by nagisa** [Byron/google-apis-rs#228]
If `google_pubsub1::Error` is used in a `failure` error as follows will be reported:

```
error[E0277]: `(dyn std::error::Error + 'static)` cannot be shared between threads safely
  --> src/main.rs:23:17
   |
23 | #[derive(Debug, Fail)]
   |                 ^^^^ `(dyn std::error::Error + 'static)` cannot be shared between threads safely
   |
   = help: the trait `std::marker::Sync` is not implemented for `(dyn std::error::Error + 'static)`
   = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<(dyn std::error::Error + 'static)>`
   = note: required because it appears within the type `std::boxed::Box<(dyn std::error::Error + 'static)>`
   = note: required because it appears within the type `google_pubsub1::cmn::Error`
   = note: required because it appears within the type `Error`
```

**Comment by Byron** [comment]
I have had a look and believe [this field in the Error type](https://github.com/Byron/google-apis-rs/blob/24b5faa4179e7c47a0e07256c86ad3e4600c10da/src/rust/api/cmn.rs#L275) is responsible for the issue.
When digging deeper, I noticed that it is populated by code like this `self.hub.auth.borrow_mut().token(self._scopes.keys())`, which goes back to the `yup-oauth2` authenticator's [`token()` method](https://docs.rs/yup-oauth2/2.0.1/yup_oauth2/struct.Authenticator.html#method.token), which itself does not implement `Send + Sync`. This certainly is an oversight, and one which can't easily be fixed in this repository.

`yup-oauth` 3.0 beta seems to be migrating to futures, which also fixes this problem. Thus I believe at some point when this repository switches to async, the issue will be fixed at last.

**Comment by nagisa** [comment]
yup_oauth is now at `3.1` so upgrading it would fix this.

**Comment by Byron** [comment]
@nagisa I took a look and as suspected, migrating from 1.0 to 3.0 is quite some non-trivial work that is likely to affect consumers of this library as well. Probably this is already a non-issue in [the next iteration](https://github.com/google-apis-rs/generator) of the google-apis, even though they are not quite ready for everyone just yet.

**Comment by Byron** [comment]
Is it compatible with `anyhow`? The `failure` crate has been deprecated I believe in favour of others.
