### ISSUE TITLE
Sheets4 throws away API error

### ISSUE THREAD

**Issue by xrl** [Byron/google-apis-rs#314]
I am learning the ropes on google sheets and I was getting a HTTP 400 error from bad request params but the response body was coming back empty.

Sheets was coming back with:

```
{
  "error": {
    "code": 400,
    "message": "Request range[A:Z] does not match value's range[A:B]",
    "status": "INVALID_ARGUMENT"
  }
}
```

which we try to deserialize to the error container:

```
#[derive(Deserialize)]
pub struct JsonServerError {
    pub error: String,
    pub error_description: Option<String>,
}
```

The API response's nested error object won't go in to a String. Which is fine if the error wasn't swallowed by: https://github.com/Byron/google-apis-rs/blob/16724d2d9be70b8f751d94402aabd01aba70baaf/gen/sheets4/src/api.rs#L6874

```
                    if !res.status().is_success() {
                        let res_body_string = client::get_body_as_string(res.body_mut()).await;

                        let json_server_error = json::from_str::<client::JsonServerError>(&res_body_string).ok();
[[[ SNIP ]]]
```

there was no easy way for me to tell what was wrong with my code because the deserialization of the error failed.

What's the best way to fix this? There is code in this same function which does a match on the error response and handles the error more elegantly. I think we need to reuse that style.

My proposed fix:
1. Update the JsonServerError to support the nested error object
2. Make the error deserialization more robust, don't swallow the error but pass it back to the user

That sound reasonable?

**Comment by FEC-bendingspoons** [comment]
Related to this, I also found that when the deserialization fails, the method will return an `Err` with the response but its body has already been consumed by the `get_body_as_string` call in the line before.

This means that both in the `Delegate` and in the `Err` that are exposed outside there is no way to even read the response. Fixing this does not solve the problem of not deserializing errors in the correct structs, but at least can give the users some ideas of what is going wrong.

**Comment by FEC-bendingspoons** [comment]
Btw I just saw the `help wanted` tag, I can try to open a PR to at least mitigate this

**Comment by Byron** [comment]
Thanks @FEC-bendingspoons, that would definitely be appreciated!

When submitting the PR please refrain from generating all APIs so it's possible to focus on the actual code changes.
When done, I think that would be an excellent time for re-releasing all crates once again, and I am looking forward to it.

**Comment by FEC-bendingspoons** [comment]
@Byron There is something that is not really clear to me: looking at [this block](https://github.com/Byron/google-apis-rs/blob/16724d2d9be70b8f751d94402aabd01aba70baaf/src/mako/api/lib/mbuild.mako#L812) we get the whole response from Google and then we deserialize the same string into 3 different struct:
- `client::JsonServerError`: this will get fed to the delegate
- `client::ServerError` (or else `client::ErrorResponse` and then accessing its `.error`): also to fed it to the delegate
- `client::ErrorResponse` (potentially again, if the previous decoding into a `ServerError` fails): this gets used as the return method for the whole `doit` call

Now, since all of this is `pub`, any change there means that this will become a breaking release (a new major). To make it worth it at that point it probably makes sense to rethink all the error types and their propagations but that seems like a lot of work.

As a workaround, we could change this line:
https://github.com/Byron/google-apis-rs/blob/16724d2d9be70b8f751d94402aabd01aba70baaf/src/mako/api/lib/mbuild.mako#L828
to something like this:
```rust
Err(_) => {
    let (parts, _) = res.into_parts();
    let body = hyper::Body::from(res_body_string);
    Err(client::Error::Failure(hyper::Response::from_parts(parts, body)))
},
``` 
it would not solve the problem of the wrongly decoded errors but would at least expose the underlying error to the user

**Comment by Byron** [comment]
Thanks for digging in! Exposing the entire error is the goal and doing it as proposed would certainly work, so I am all for it.

What do you think about the idea of making the deserialization more flexible by adding [catch-all fields](https://serde.rs/attr-flatten.html#capture-additional-fields)? This could be done on top of what you are proposing, returning structured errors when possible but falling back to returning the actual response if all that fails as well.

In any case, if you want to get started with this, PRs are welcome.

**Comment by FEC-bendingspoons** [comment]
> doing it as proposed would certainly work, so I am all for it

Good to know, I can try to open a PR with that easy fix soon (today or tomorrow)

> What do you think about the idea of making the deserialization more flexible by adding [catch-all fields](https://serde.rs/attr-flatten.html#capture-additional-fields)?

I think that the problem here is that the current error structs have fields that the actual responses from GCP don't have, so adding a catch-all field will not improve the solution.

If we were to go for the breaking change route, I propose ditching the 3 error structs and just return a `serde_json::value::Value`. WDYT?

**Comment by Byron** [comment]
Alright, let's do it. Fix error handling in a breaking way and ready for a breaking release. 

Thanks for your help.

**Comment by FEC-bendingspoons** [comment]
Ok cool. I'll try to do both in a single PR soon:
- if the response a valid json we return a single `serde_json::value::Value` both in the delegate and as the argument of the error
- otherwise we just return the response with the correct body

**Comment by FEC-bendingspoons** [comment]
I've opened a PR, let me know what you think 🙏🏻

**Comment by Byron** [comment]
Everything should have been republished, can you check if it works for you?

**Comment by FEC-bendingspoons** [comment]
I am using `google-pubsub1` and I can confirm that it works for me, THANK YOU

**Comment by Byron** [comment]
Great to hear, and thanks everyone for their help without which this issue would still be open.
