### ISSUE TITLE
yup_oauth2 versions inconsistent with different APIs

### ISSUE THREAD

**Issue by kolemikko** [Byron/google-apis-rs#357]
Hey,

I'm working on a project where I'm using both Sheets4 API and Drive3 API, I wanted to create one authenticator handling credentials and tokenStorage etc. for both of them and noticed that [sheets4 is using yup_oauth2 version 6.6](https://github.com/Byron/google-apis-rs/blob/main/gen/sheets4/Cargo.toml) whereas [drive3 is using version 7.0](https://github.com/Byron/google-apis-rs/blob/main/gen/drive3/Cargo.toml). Unfortunately because of this mismatch I would need to create one authenticator each. I haven't checked many other APIs but it seems like most of them use yup_oauth2 7.0, so maybe worth checking this out throughout the project.

**Comment by Byron** [comment]
Sorry for that! The inconsistency is due to me selectively publishing crates as demanded to not unnecessarily spam the crates.io database.

Thus I have once again selectively republished the `google_sheets4` crate which now exists as [version 4](https://crates.io/crates/google-sheets4/4.0.1+20220221) as well.

I am currently republishing all crates which should fix this issue for good. Please let me know if there is anything else.

**Comment by kolemikko** [comment]
Thanks a lot for fast update!

I totally understand, all good now! :)
