### ISSUE TITLE
Allow user to provide credentials directly

### ISSUE THREAD

**Issue by philippeitis** [Byron/google-apis-rs#362]
I'm trying to rewrite a Python server-side application which interfaces with Google Drive in Rust, but am running into issues using the provided google-apis-rs crates, as I need to pass an Authenticator, and not the credentials directly. 
 
In a server-side authorization, the authorization implementation should allow the server itself to redirect the user, and provide endpoints to receive the redirect from the oauth server - however, the following code (in the implementation) does not actually allow this (since the server does not handle where/how the token is generated):

```rust
            let token = match self.hub.auth.token(&self._scopes.keys().collect::<Vec<_>>()[..]).await {
                Ok(token) => token.clone(),
                Err(err) => {
                    match  dlg.token(&err) {
                        Some(token) => token,
                        None => {
                            dlg.finished(false);
                            return Err(client::Error::MissingToken(err))
                        }
                    }
                }
            };
```
https://github.com/Byron/google-apis-rs/blob/f279d821e1367d7b8026bed4a43c5dac44a63e99/gen/drive3/src/api.rs#L3290

This is fine for single-user situations, but makes it very difficult to use the library for me. It would be great if we could handle authentication separately, and provide credentials to the API directly.

With the changes I'm proposing, the usage might look like this (similar to how it's implemented here: https://developers.google.com/identity/protocols/oauth2/web-server#example):

```rust
let credentials = oauth2::InstalledFlowAuthenticator::builder(
        secret,
        oauth2::InstalledFlowReturnMethod::HTTPRedirect,
    ).build().await.unwrap().token(...).await.unwrap();
let mut hub = DriveHub::new(hyper::Client::builder().build(hyper_rustls::HttpsConnectorBuilder::new().with_native_roots().https_or_http().enable_http1().enable_http2().build()), credentials);

let result = hub.files().list()
             .team_drive_id("eos")
             .supports_team_drives(false)
             .supports_all_drives(true)
             .spaces("duo")
             .q("sed")
             .page_token("no")
             .page_size(-15)
             .order_by("kasd")
             .include_team_drive_items(true)
             .include_permissions_for_view("et")
             .include_items_from_all_drives(true)
             .drive_id("vero")
             .corpus("erat")
             .corpora("sed")
             .doit().await;
```

If the user expects the credentials to expire, they can use a loop to re-authorize:
```rust
let auth = oauth2::InstalledFlowAuthenticator::builder(
        secret,
        oauth2::InstalledFlowReturnMethod::HTTPRedirect,
    ).build().await.unwrap();

let client = hyper::Client::builder().build(hyper_rustls::HttpsConnectorBuilder::new().with_native_roots().https_or_http().enable_http1().enable_http2().build());

loop {
    let credentials = auth.token(...).await.unwrap();
    let mut hub = DriveHub::new(client, credentials);
    // You can configure optional parameters by calling the respective setters at will, and
    // execute the final call using `doit()`.
    // Values shown here are possibly random and not representative !
    let result = hub.files().list()
             .team_drive_id("eos")
             .supports_team_drives(false)
             .supports_all_drives(true)
             .spaces("duo")
             .q("sed")
             .page_token("no")
             .page_size(-15)
             .order_by("kasd")
             .include_team_drive_items(true)
             .include_permissions_for_view("et")
             .include_items_from_all_drives(true)
             .drive_id("vero")
             .corpus("erat")
             .corpora("sed")
             .doit().await;
 
    match result {
        Err(e) => match e {
            Error::MissingAPIKey
            |Error::MissingToken(_) => continue,
            e => println!("{}", e)
         }
         Ok(res) => println!("Success: {:?}", res),
     }
}
```

This could also make it possible to plug in other oauth libraries, such as `oauth2`, which could be a useful feature for some people.

I'd be happy to try implementing these changes, but given that this would result in significant / breaking changes to the APIs presented by the various crates in the repository, I feel it would a be good idea to get some feedback first.

**Comment by Byron** [comment]
Thanks for letting me know and for the clear explanation of what's needed.

My memory on this is fuzzy, but I always thought it's possible to pass a token or credentials to any call as well - maybe I am mistaken though. 

In any case, since the authenticator is already behind a trait, it should be possible to implement token in any way desired, which would make it possible to implement what you need related to token acquisition.

As for an authentication-retry loop, I thought there was a loop for this already as well, but maybe that's only implemented for file-uploads or the likes. In that case, I think it should be possible to add such a feature in a non-breaking way. I remember there was a way to specify a delegate which can control how often it should retry, for example, and maybe that can come in handy here as well.

If my vagueness didn't discourage you too much and you think making the situation better can be done without vast breaking changes, a PR is certainly appreciated.

**Comment by philippeitis** [comment]
From my inspection of the source code, the authenticator is a struct, not a trait (https://docs.rs/yup-oauth2/latest/src/yup_oauth2/authenticator.rs.html#36), and the authenticator struct does not allow user provided authenticators.

It's possible to use a custom delegate to provide an API token, but the problem is you still need to pass an authenticator, which forces you into the `yup-oauth2` flows, which is undesirable as per the previous discussion (due to incompleteness, and additional dependencies).

Ideally, there would be a common crate (eg. `google-api-rs-auth-structs`) providing a `TokenProvider` trait and `AccessToken` struct with appropriate methods. The `TokenProvider` trait can be by default implemented for `yup_oauth2::Authenticator` (as you'd expect, using the .token() method), and for `AccessToken`, both of which could return themselves. `TokenProvider` would then replace `Authenticator` as the input to methods like `DriveHub::new`

```rust
#[derive(Clone)]
struct AccessToken {
    pub token: String
}

impl AccessToken {
     fn new(token: String) -> Self {
        Self { token }
    }
}

trait TokenProvider {
     fn token(...) -> Result<AccessToken, ...>;
}

impl TokenProvider for Authenticator {
     fn token(...) -> Result<AccessToken, ...> {
         self.token(...).await
     }
}

impl TokenProvider for AccessToken {
    fn token(...) -> Result<AccessToken, ...> {
        Ok(self.clone)
    }
}
```


This change would decouple the API crates from `yup-oauth2`, which I think would be an incredibly valuable change. Accordingly, it would make sense to feature-gate `yup-oauth2` (and set it as a default feature). This would allow users to choose an easy default implementation, or an implementation that fits their specific needs without having to spend an excessive amount of time figuring out these implementation details as I have.

I'd also, of course, include documentation / examples about how users can implement their own oauth flow to make their lives easier as well.

**Comment by Byron** [comment]
> From my inspection of the source code, the authenticator is a struct, not a trait (https://docs.rs/yup-oauth2/latest/src/yup_oauth2/authenticator.rs.html#36), and the authenticator struct does not allow user provided authenticators.

Indeed! Thanks for the clarification.

> It's possible to use a custom delegate to provide an API token, but the problem is you still need to pass an authenticator, which forces you into the yup-oauth2 flows, which is undesirable as per the previous discussion (due to incompleteness, and additional dependencies).

All that is true! There is some hope even for the current implementation though thanks to [this portion of code](https://github.com/Byron/google-apis-rs/blob/f279d821e1367d7b8026bed4a43c5dac44a63e99/gen/groupsmigration1/src/api.rs#L367:L379) which has a delegate handle the token if the authenticator fails, and does so in a loop as well with the [looping being controlled by the delegate](https://github.com/Byron/google-apis-rs/blob/f279d821e1367d7b8026bed4a43c5dac44a63e99/gen/groupsmigration1/src/api.rs#L408:L408).

If one was able to configure the yup-oauth2 authenticator to immediately fail without contacting any server, the authentication would effectively be controlled by the delegate.

This is something I'd try before giving up or making big changes. If that generally works, the delegate could easily and in a backward compatible way be upgraded if more flow control is needed.

> This change would decouple the API crates from yup-oauth2, which I think would be an incredibly valuable change. Accordingly, it would make sense to feature-gate yup-oauth2 (and set it as a default feature). This would allow users to choose an easy default implementation, or an implementation that fits their specific needs without having to spend an excessive amount of time figuring out these implementation details as I have.

I agree! As a transition step for a final transition that might never happen because it works for you, I could imagine providing some sort of 'dummy authenticator' which is merely a function that configures a yup-oauth2 authenticator so that it fails, paired with an implementation of a delegate which makes different token acquisition strategies easier to achieve.

> I'd also, of course, include documentation / examples about how users can implement their own oauth flow to make their lives easier as well.

Thank you, much appreciated! If you want to go all in on the decoupling, I think you could and believe this would be backwards compatible as well. Maybe it's faster to (at least as PoC) go with the more hacky alternative proposed here, and that's definitely good for a PR as well. I leave the choice to you and look forward to a PR should you go ahead with any of it.
