### ISSUE TITLE
Bazel Support

### ISSUE THREAD

**Issue by silicon-ninja** [Byron/google-apis-rs#447]
Hey i was wondering we can move this project to use `bazel` ? since all the projects at google use `bazel` would be easy to compile the code. Thanks.

**Comment by Byron** [comment]
I think Google should adopt this project or make their own and in the process change it however they see fit.

Right now using any crate provided by this project is as easy as adding a dependency in `cargo` manifests, so I don't think it matters how the crate is produced.

Thus, job orchestration isn't a problem that needs solving, and if something needs a rewrite than it's the python generator and how it's launched - it keeps breaking over time just because the ecosystem changes in breaking ways :/.

Thanks for your understanding.

**Comment by silicon-ninja** [comment]
i was thinking to raise a PR if you were okay with it sometime.

**Comment by Byron** [comment]
If `bazel` replaces `make` I don't think there is much value as `make` historically hasn't been a problem in this project.

I also don't think that `bazel` will make this project more attractive to Google as I think they'd rather rebuild than reuse.
So no matter how I try to see it, I'd suggest not to invest time in this.

Thanks for your understanding.
